site_name: Jarrod
site_url: https://jarrod.md
repo_name: jarrodb.github.io
repo_url: https://github.com/jarrodb/jarrodb.github.io
theme:
  name: material
#  logo: assets/jarrod.png
#  palette:
#    primary: white
#    accent: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - header.autohide
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/favicon-32x32.png

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - def_list
  - tables
  - abbr
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - awesome-pages
#  - minify:
#      minify_html: true
