name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper deployment
      - name: Configure Git Credentials
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the git directory
          git config --global user.name github-actions[bot]
          git config --global user.email j@rrod.io
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: mkdocs gh-deploy --force
